### ISSUE TITLE
JETTest failing with Julia 1.7

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#170]
e.g. https://github.com/CliMA/ClimaCore.jl/runs/3576785543

@vchuravy @aviatesk any idea what the cause could be?

**Comment by aviatesk** [comment]
Which Julia version is used ? It's not compatible with the latest v1.7-rc and nightly (because I decided to deprecate JETTest.jl from the next JET.jl release). I'll try to make the next release this week or next week, but for the meanwhile could you turn that test off ? I can make a PR on this repo with updates.

**Comment by simonbyrne** [comment]
Ah, thanks! Our 1.7 tests are mainly used to find potential problems, so we don't worry too much about them.
