### ISSUE TITLE
NetCDF export

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#481]
We need a basic mechanism to export to Lat/Long/height NetCDF files

Initially for height we can just use Z coordinates (at least until we have topography). So the rough process would be:

- regrid to a latlong grid (initially using TempestRemap)
- convert velocity to UVW
- save as 4D (lat, long, height, time) NetCDF file using [CF conventions](https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html).

It would be helpful if I could see a sample NetCDF file which uses a similar convention.

cc: @jiahe23

**Comment by jiahe23** [comment]
@szy21  has prepared an output that should be accessible on caltech central.

**Comment by jakebolewski** [comment]
Tempest saves the output in CF conventions (basically everything above holds true).

**Comment by simonbyrne** [comment]
Okay, so I think the main things we need to do
1. be able to export spectral grid in a format that `ApplyOfflineMap` can process
2. create some wrapper functions for the TempestRemap utilities

**Comment by jakebolewski** [comment]
Yes that sounds right, if you do the vector conversion on output for the cubed sphere grid everything else should be able to be handled by tempest remap.

**Comment by jakebolewski** [comment]
That also holds true for remapping the vertical (for stretched grids).

**Comment by simonbyrne** [comment]
Yes, that makes sense. I'm just not sure of the ordering of the data:
@paullric: how are the GLL nodes ordered (for both `cgll` and `dgll`)? Also `meta_src`/`meta_dest` seems to allow for spectral element metadata: what format should that be in?

**Comment by paullric** [comment]
For dgll:  Element quadrilaterals are specified via counter-clockwise ordering of vertices (X[0],X[1],X[2],X[3]).  The first four Gauss Lobatto nodes are along the edge (X[0],X[1]).  The vertices are then "stacked" upon those vertices until the last vertices are along the edge (X[3],X[2]).

For cgll:  As with dgll except you need to retain a look-up table of vertices as they're added.  If a particular vertex has already been added as part of another element (i.e., if it's shared because it's at a corner or along an edge) then you use that index instead.

Regarding meta_src/meta_dst that's not really used.  The read/write routines can be found in "GenerateOfflineMap".

**Comment by jakebolewski** [comment]
Nodes are ordered in row major by default, but if you use the HOMME format flag IIRC it will re-order the output to column major convections ("fortran order"). 

It's useful to look at the test functions: https://github.com/ClimateGlobalChange/tempestremap/blob/ef08aeeceb710f9dd2c85b5c3de6fb19d9795e9d/src/GenerateTestData.cpp#L484

as then it is clearer how things are put together (maybe creating one of these ourselves as a field would be a good step to a full integration test)

**Comment by simonbyrne** [comment]
Since we store shared nodes redundantly, the DGLL one would be easier, but I hit an error: https://github.com/ClimateGlobalChange/tempestremap/issues/98
