### ISSUE TITLE
Make `x3boundary` less error prone

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#54]
`x3boundary` in `IntervalDomain` is, by default, `(:left, :right)`. This can cause confusion in drivers if it seems that the interp/gradient kwargs can be arbitrarily named.

I think simply removing the default would be a simple fix.

**Comment by simonbyrne** [comment]
See #52

**Comment by jakebolewski** [comment]
I think the problem here is that the gradient constructor doesn't really know about the domain, it is matched fairly late. 

One immediate improvement would be to probably not have defaults for the domain and explicitly require the correct number of boundary labels, that forces them to be specified.

We probably could throw an error during the instantiate part of the stencil setup where the applied BC in the expression operators would be checked against the spaces.  Not sure how best to handle that this case.
